### ISSUE TITLE
Saved Model does not exist

### ISSUE THREAD

**Issue by OFranke** [bundesAPI/deutschland#8]
I am receiving following error message, it looks like the model used to solve the captchas does not exist in `assets/model.h5` directory: `OSError: SavedModel file does not exist at: assets/model.h5/{saved_model.pbtxt|saved_model.pb}`

Here's my code:
```
from deutschland import Bundesanzeiger
ba = Bundesanzeiger()
# search term
data = ba.get_reports("Deutsche Bahn AG")
# returns a dictionary with all reports found as fulltext reports
print(data.keys())
# dict_keys(['Jahresabschluss zum Geschäftsjahr vom 01.01.2020 bis zum 31.12.2020', 'Konzernabschluss zum Geschäftsjahr vom 01.01.2020 bis zum 31.12.2020\nErgänzung der Veröffentlichung vom 04.06.2021',

```

**Comment by tmechen** [comment]
problem: installing the lib places the model in here: `/venv/lib/site-packages/assets/model.h5` 

(hacky) fix:
* place the model.h5 file into `venv/lib/site-packages/deutschland/bundesanzeiger/assets/model.h5`
* replace the load_model() in [model.py ](https://github.com/bundesAPI/deutschland/blob/main/deutschland/bundesanzeiger/model.py#L36) with:
```python
def load_model():
    parent = Path(os.path.abspath(__file__)).parent
    path = os.path.join(parent, 'assets', 'model.h5')
    return keras.models.load_model(
        path, custom_objects={"my_accuracy": my_accuracy}
    )
```
no pull request because there might be some better solution than this (i hope), i did never distribute files via libraries.
